export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;

export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;

export const CHANGE_MESSAGE = 'CHANGE_MESSAGE';
export type CHANGE_MESSAGE = typeof CHANGE_MESSAGE;

export const CHANGE_TYPE = 'CHANGE_TYPE';
export type CHANGE_TYPE = typeof CHANGE_TYPE;